apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: Repository
metadata:
  name: hono-pds
  namespace: default
spec:
  source: {}
  branch: fix/crawler-announce-retries
  verify:
  - bash
  - -c
  - git checkout origin/pre-iroh -- deno.lock 2>/dev/null || true; deno task test
    --no-lock
  populate:
    partition: directory
    summarize: true
    root: true
status:
  headCommit: e756842ffe022ad5e8a5b8b5f127756d1ca085ad
  indexedCommit: e756842ffe022ad5e8a5b8b5f127756d1ca085ad
  observedCommit: e756842ffe022ad5e8a5b8b5f127756d1ca085ad
  phase: Populated
  contexts:
    total: 16
    summarized: 16
    failed: 0
