apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: Repository
metadata:
  name: hono-pds
  namespace: default
spec:
  source: {}
  branch: fix/crawler-announce-retries
  verify:
  - deno
  - test
  populate:
    partition: directory
    summarize: true
    root: true
status:
  headCommit: fa8920306bc4e01b3deea023d3114f6239813f7d
  indexedCommit: fa8920306bc4e01b3deea023d3114f6239813f7d
  observedCommit: fa8920306bc4e01b3deea023d3114f6239813f7d
  syncedCommit: fa8920306bc4e01b3deea023d3114f6239813f7d
  phase: Populating
  contexts:
    total: 16
    summarized: 2
    failed: 0
