apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SpecChange
metadata:
  name: test-common-c2s-fa8920306bc4-fa8920306bc4
  namespace: default
spec:
  systemContext: test-common
  direction: CodeToSpec
  fromCommit: fa8920306bc4e01b3deea023d3114f6239813f7d
  toCommit: fa8920306bc4e01b3deea023d3114f6239813f7d
status:
  phase: Running
  message: the agent is summarizing test-common
