apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SystemContext
metadata:
  name: lib-atproto-repo-deno
  namespace: default
spec:
  repository: hono-pds
  upstream: self
  dependsOn:
  - sc.hono-pds
codeRefIndex:
- file:lib/atproto-repo-deno/account-store.ts account-store.ts@lib/atproto-repo-deno/account-store.ts
- file:lib/atproto-repo-deno/car.ts car.ts@lib/atproto-repo-deno/car.ts
- file:lib/atproto-repo-deno/deno-kv-storage.ts deno-kv-storage.ts@lib/atproto-repo-deno/deno-kv-storage.ts
- file:lib/atproto-repo-deno/indexeddb-storage.ts indexeddb-storage.ts@lib/atproto-repo-deno/indexeddb-storage.ts
- file:lib/atproto-repo-deno/memory-storage.ts memory-storage.ts@lib/atproto-repo-deno/memory-storage.ts
- file:lib/atproto-repo-deno/mod.ts mod.ts@lib/atproto-repo-deno/mod.ts
- file:lib/atproto-repo-deno/repo.ts repo.ts@lib/atproto-repo-deno/repo.ts
- file:lib/atproto-repo-deno/service-auth.ts service-auth.ts@lib/atproto-repo-deno/service-auth.ts
- file:lib/atproto-repo-deno/signer.ts signer.ts@lib/atproto-repo-deno/signer.ts
