apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SystemContext
metadata:
  name: lib-common-oauth-server-common
  namespace: default
spec:
  repository: hono-pds
  upstream: self
  dependsOn:
  - sc.hono-pds
codeRefIndex:
- file:lib/common/oauth-server-common/mod.ts mod.ts@lib/common/oauth-server-common/mod.ts
