apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SystemContext
metadata:
  name: test-hono-factory
  namespace: default
spec:
  repository: hono-pds
  upstream: self
  dependsOn:
  - sc.hono-pds
codeRefIndex:
- file:test/hono-factory/e2e_test.ts e2e_test.ts@test/hono-factory/e2e_test.ts
